### ISSUE TITLE
Explanation of how python understands Codesys data types

### ISSUE THREAD

**Issue by Chaser** [arwie/controlOS_demo#3]
The python code shows two structs are passed and decoded in python

https://github.com/arwie/controlOS_demo/blob/adec7a47238b157b0ad798f48577dac5995b75b7/root/local_src/python-shared/shared/app/codesys.py#L28-L29

Its not clear how these structures are populated? Can you explain how codesys exposes this information?

**Comment by arwie** [comment]
I will make a small example soon which will demonstrate this feature.

**Comment by arwie** [comment]
Check out codesys/controlOS_demo.project:

```
PROGRAM app
VAR_OUTPUT
	cmd: AppCmd;
END_VAR
VAR_INPUT
	fbk: AppFbk;
END_VAR

IF SysSemProcessEnter(sem, 0) = 0 THEN
	SysSharedMemoryRead (shm,           0, ADR(cmd), SIZEOF(cmd), ADR(iec_result));
	SysSharedMemoryWrite(shm, SIZEOF(cmd), ADR(fbk), SIZEOF(fbk), ADR(iec_result));
	SysSemProcessLeave(sem);
END_IF
```

**Comment by Chaser** [comment]
Hi the codesys component of it makes sense. 

However, the question was specifically about how the python code "knows" / figures out the structure size and fields. 

In the python there is a function `parse_struct`

https://github.com/arwie/controlOS_demo/blob/adec7a47238b157b0ad798f48577dac5995b75b7/root/local_src/python-shared/shared/app/codesys.py#L28-L29

Parse struct though relies on a file called `/usr/share/codesys/{name}.struct'. 

https://github.com/arwie/controlOS_demo/blob/adec7a47238b157b0ad798f48577dac5995b75b7/root/local_src/python-shared/shared/codesys.py#L51

How is this file created? This isn't a standard file as part of codesys so must have been generated? What is the contents of this file? Are they just codesys exports?

**Comment by arwie** [comment]
The .struct files are copied to the target together with the codesys boot application:
https://github.com/arwie/controlOS_demo/tree/youtube_2023-12-09/root/projectroot/opt/codesys/PlcLogic/Application

They are just exports of the codesys structs as text files. 
This codesys (python) script does this:
https://github.com/arwie/controlOS_demo/blob/youtube_2023-12-09/codesys/deploy_multi.py

https://github.com/arwie/controlOS_demo/blob/0e0e39292995e6fd825cda3be3fd5d7a635c1123/codesys/deploy_multi.py#L47-L50

**Comment by Chaser** [comment]
Thanks - thats makes sense, it was exported and read based on these files. Appreciate the explanation.
